### ISSUE TITLE
Unable to deploy with new manifest style

### ISSUE THREAD

**Issue by amalagaura** [HappyTobi/cf-puppeteer#15]
@HappyTobi  Thanks for help with --legacy-push. We are using that and it looks good so far!

I wanted to upgrade my manifest since the old syntax is deprecated.

This is our `manifest.preview.yml`
```
---
defaults: &defaults
  memory: 1G
  disk_quota: 1G
  buildpacks:
    - ruby_latest_buildpack
  env:
    RAILS_ENV: preview
  services:
    - postgres
    - redis
applications:
  - name: app-test
    <<: *defaults
    command: rails s -p $PORT -e $RAILS_ENV
    env:
      ENABLE_SCHEDULER: true
  - name: sidekiq
    <<: *defaults
    health-check-type: process
    no-route: true
    command: sidekiq -C config/sidekiq.yml
```

A regular `cf push` does work. But we get the following with

```
cf zero-downtime-push app-test -f manifest.preview.yml  --no-start
```

```
Applying manifest manifest.preview.yml in org DIDIT / space preview as ankur.sethi@...
Buildpack "ruby_latest_buildpack" must be an existing admin buildpack or a valid git URI
FAILED
FAILED
error while uploading / deploying the application... roll everything back
```
