### ISSUE TITLE
Command defaults to --no-route and --no-start

### ISSUE THREAD

**Issue by iKrushYou** [HappyTobi/cf-puppeteer#24]
For some reason, it looks like it's defaulting to `--no-route` and `--no-start` even though I don't specify it
```
compass-api akrush$ cf zero-downtime-push compass -f manifest-dev.yaml --legacy-push
Deleting app compass in org TZU0 / space tzu0_dev as akrush...
OK
Use legacy push
start pushing application with arguments [push compass -f manifest-dev.yaml --no-start --no-route]
```
```yaml
---
default_envs: &default_envs
  SPRING_PROFILES_ACTIVE: cloud,dev
  TZ: GMT
defaults: &defaults
  buildpacks:
    - java_buildpack_offline
  env:
    *default_envs
  timeout: 120
  services:
    - jasypt-service
applications:
  - name: armada-compass
    <<: *defaults
    path: target/compass-0.0.1-SNAPSHOT.jar
```

Update: It seems like those flags specified in the output are a red herring. However, I can't explain how but now the app seems to start on its own. I have also found that the route only pushes if it's explicitly set. It won't push a default route if I leave the routes blank. Is there a way around this?
