### ISSUE TITLE
push does not stop if the upload fails

### ISSUE THREAD

**Issue by ghost** [HappyTobi/cf-puppeteer#9]
We are trying a push with

`CF_PUPPETEER_TRACE=true cf zero-downtime-push app` so using v3.

It is unable to stage. Using the trace we see this:

```
response from get call to path: /v3/builds/ was: {   "pagination": {      "total_results": 11804,      "total_pages": 237,      "first": {         "href": "https://api.system.pcf-test.com/v3/builds?page=1&per_page=50" 
```
Repeated continuously.

Two problems:
1. It never goes beyond page=1
2. We have 11k builds. I don't know if that is because we are not cleaning up something or it is normal. Assuming the plugin is looking for a build, it seems there should be some criteria added so that it doesn't have to page through looking for a specific entry. Even a reverse sort should be sufficient. 

I have not looked at the code to see what this part is looking for.

**Comment by ankursethi-uscis** [comment]
OK in an effort to provide more information since I see the code adds a build-guid I was going through the trace and found this

```
 "state": "FAILED",         "error": "InsufficientResources - Insufficient resources",  
```

So I think we failed in a previous step. Then the build-guid is blank, so it keeps calling the /v3/builds

**Comment by ghost** [comment]
I see this in the Create build phase

```
"error": "The app upload is invalid: Invalid zip archive.",      "checksum": {         "type": "sha256",         "value": null      }   },   "state": "FAILED",  
```

So I think it failed there and then the push does not stop.

```
create build
response from get call to path: /v3/builds was: %!s(<nil>)
```

I see the code queries /v3/builds with a guid, but it seems the guid is blank so it is making a request without a guid and then just looping.

**Comment by ghost** [comment]
```
$ cf --version
cf version 6.45.0+5f9ff16f9.2019-06-03

And zero-downtime-push version 1.1.1
```
      "cloud_controller_v2": {
         "meta": {
            "version": "2.120.0"
         }
      },
      "cloud_controller_v3": {
         "meta": {
            "version": "3.55.0"
         }
```

**Comment by HappyTobi** [comment]
Hi @ankursethi-uscis thx for the Feedback, i already see the issues with the error handling. I try to look into that issue asap

**Comment by HappyTobi** [comment]
> ```
> $ cf --version
> cf version 6.45.0+5f9ff16f9.2019-06-03
> 
> And zero-downtime-push version 1.1.1
> ```
> 
> ```
>   "cloud_controller_v2": {
>      "meta": {
>         "version": "2.120.0"
>      }
>   },
>   "cloud_controller_v3": {
>      "meta": {
>         "version": "3.55.0"
>      }
> ```
Your version is ok thanks!

I started to fix the issue hope that i can release a new version soon

**Comment by HappyTobi** [comment]
Hi @ankursethi-uscis i found the issue.
I will create a new pre-release (1.1.2) can you check that an give me some feedback?
Kind regards

**Comment by ghost** [comment]
@HappyTobi I think it looks good so far. So our problem must be that we have a manifest that is not v3 compatible:


```
cf zero-downtime-push app -f manifest.yml --show-crash-log

start uploading manifest file
FAILED
Error while calling the apply manifest url /actions/apply_manifest - error: Post /actions/apply_manifest: unsupported protocol scheme ""
FAILED
error while uploading / deploying the application... roll everything back
Deleting app app in org ORG / space space as ankur.sethi
OK
App app does not exist.
Renaming app app-venerable to space in org ORG / space space as ankur.sethi...
OK
FAILED
error: Post /actions/apply_manifest: unsupported protocol scheme ""
```

So I think it is ok. I just tried with: `--legacy-push` and it did work. 

What I will do next is upgrade our manifest and then try a push. But you probably tried that which was working.

**Comment by ghost** [comment]
@HappyTobi There is still some other error. I switched to our v3 manifest and used `cf push` and it works. But when I use `zero-downtime-push` I get the same error

```
response from POST call - path: /v3/apps was: %!s(<nil>)
start uploading manifest file
try to call path: /actions/apply_manifest
FAILED
Error while calling the apply manifest url /actions/apply_manifest - error: Post /actions/apply_manifest: unsupported protocol scheme ""
FAILED
error while uploading / deploying the application... roll everything back
```

**Comment by HappyTobi** [comment]
can you show me your manifest file?

**Comment by ghost** [comment]
```
---
defaults: &defaults
  memory: 1G
  disk_quota: 1G
  buildpacks:
    - ruby_latest_buildpack
  env:
    RAILS_ENV: preview
    SOLR_URL: https://abcd.com/solr/core
  services:
    - postgres
    - redis
applications:
  - name: app
    <<: *defaults
    env:
      ENABLE_SCHEDULER: true
    command: rake db:seed_or_migrate && rails s -p $PORT -e $RAILS_ENV
  - name: sidekiq
    <<: *defaults
    health-check-type: process
    no-route: true
    command: sidekiq -q default -q mailers
```

**Comment by ghost** [comment]
Is it a manifest problem or an error with a URL location on where to send the manifest?

**Comment by HappyTobi** [comment]
I think it‘s the Manifest.
Also multiple applications wouldn‘t be deployed but i will also bring that in the new release

**Comment by ghost** [comment]
This manifest does work with `cf push`. I did specify one application on the command line for zero-downtime-push since it was required.

**Comment by HappyTobi** [comment]
super late sorry @ankursethi-uscis
i changed a lot in the new 1.2.1rc1 release so hope you can try it again and you don't have any issues anymore

**Comment by amalagaura** [comment]
@HappyTobi Thanks! I will check this out.

**Comment by amalagaura** [comment]
@HappyTobi We don't get the same manifest parsing error. But now we get this:

`Buildpack "ruby_latest_buildpack" must be an existing admin buildpack or a valid git URI`

But our buildpack *does* exist for our cflinuxfs3 stack and a regular `cf push` does work. I looked at your parsed yaml file in the temp directory and parsed it and the yaml is good. The buildpacks comes out as a proper array.

**Comment by HappyTobi** [comment]
Hi @amalagaura can you try two things please:
1. Push your app with the  --legacy-push option
2. Is ist working when you are using 
2.1 v3-create-app
2.2 v3-apply-manifest
2.3 v3-push

Can you tell me if both things are working?
Please use the latest version i fixed the error handling to give you a better feedback whats happened

Kind regards Tobi

**Comment by amalagaura** [comment]
Hi Tobi

1. --legacy-push is working. I thought it wouldn't because our manifest has the new syntax.
2.1 Works
2.2 Fails with the same error message

I upgraded to the latest cf that our platform has but we are on the following

api version:    2.120.0
cf version 6.46.1+4934877ec.2019-08-23

**Comment by HappyTobi** [comment]
@amalagaura
Can you post you manifest? Then we can find out why we have an issue here

**Comment by amalagaura** [comment]
@HappyTobi 

The manifest is pretty much the same as before.

```
---
defaults: &defaults
  memory: 1G
  disk_quota: 1G
  buildpacks:
    - ruby_latest_buildpack
  env:
    RAILS_ENV: preview
    SOLR_URL: https://a.url.com/solr/core
  services:
    - postgres
    - redis
applications:
  - name: app
    <<: *defaults
    command: rake db:seed_or_migrate && rails s -p $PORT -e $RAILS_ENV
    env:
      ENABLE_SCHEDULER: true
  - name: sidekiq
    <<: *defaults
    health-check-type: process
    no-route: true
    command: sidekiq -C config/sidekiq.yml

```

I think the problem is not with your code. Your code seems to be parsing the yml correctly. I think the problem is with our version of PCF. We are on 2.3 right now. My guess is they have fixed v3-apply-manifest in the later versions. I think that is the command your plugin is running since that is failing.
